FROM python:3.12-slim

COPY --from=ghcr.io/astral-sh/uv:0.12.0 /uv /uvx /bin/

COPY orders/app.py /app/
COPY pyproject.toml uv.lock /app/

WORKDIR /app

RUN uv sync --locked --no-dev

ENV FLASK_APP=app.py
ENV PATH="/app/.venv/bin:$PATH"

CMD ["flask", "run", "--host=0.0.0.0"]
